version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-devops
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node-api:
    build: ./node-api
    container_name: node-devops
    restart: always
    env_file:
      - .env
    ports:
      - "${NODE_PORT}:3000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: fe-devops
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - node-api

volumes:
  db_data: